# Generated by Django 5.0.1 on 2024-01-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_type',
        ),
    ]
