# Generated by Django 5.0.1 on 2024-01-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_delete_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
    ]
