# Generated by Django 5.0.1 on 2024-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_district_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=50)),
            ],
        ),
    ]
