# Generated by Django 5.0.1 on 2024-02-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Place',
        ),
    ]
