# Generated by Django 5.0.1 on 2024-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Intenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changepassword_name', models.CharField(max_length=50)),
            ],
        ),
    ]
