# Generated by Django 5.0.1 on 2024-02-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_tbl_intenship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Changepassword',
        ),
        migrations.RenameField(
            model_name='tbl_intenship',
            old_name='changepassword_name',
            new_name='Intenship_name',
        ),
    ]
