# Generated by Django 5.0.1 on 2024-02-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_delete_tbl_changepassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Intenship',
        ),
    ]
