# Generated by Django 5.0.1 on 2024-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0004_delete_tbl_intenship'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Intenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intenship_duration', models.CharField(max_length=50)),
                ('Intenship_details', models.CharField(max_length=50)),
                ('Intenship_poster', models.FileField(upload_to='Company_photo/')),
            ],
        ),
    ]
