# Generated by Django 5.0.1 on 2024-02-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_initial'),
        ('Guest', '0015_tbl_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_intenship',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company'),
        ),
    ]
