# Generated by Django 5.0.1 on 2024-02-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_User',
        ),
    ]
