# Generated by Django 5.0.1 on 2024-02-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.FileField(upload_to='User_photo/')),
            ],
        ),
    ]
