# Generated by Django 5.0.1 on 2024-02-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Company',
        ),
    ]
