# Generated by Django 5.0.1 on 2024-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_delete_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_photo', models.FileField(upload_to='Company_photo/')),
            ],
        ),
    ]
