# Generated by Django 5.0.1 on 2024-02-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Company',
        ),
        migrations.DeleteModel(
            name='tbl_User',
        ),
    ]
