# Generated by Django 5.0.1 on 2024-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_delete_tbl_company_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.IntegerField(max_length=12)),
                ('user_email', models.TextField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_district', models.CharField(max_length=50)),
                ('user_place', models.CharField(max_length=50)),
                ('user_proof', models.FileField(upload_to='User_proof/')),
                ('user_photo', models.FileField(upload_to='User_photo/')),
                ('user_password', models.TextField(max_length=50)),
            ],
        ),
    ]
