# Generated by Django 5.0.1 on 2024-02-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_district',
        ),
    ]
