# Generated by Django 5.0.1 on 2024-02-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_remove_tbl_user_user_place_tbl_user_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_User',
        ),
    ]
