# Generated by Django 5.0.1 on 2024-02-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_place'),
        ('Guest', '0011_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=12)),
                ('user_email', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_proof', models.FileField(upload_to='User_proof/')),
                ('user_photo', models.FileField(upload_to='User_photo/')),
                ('user_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
