# Generated by Django 5.0.1 on 2024-02-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_place'),
        ('Guest', '0014_delete_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=12)),
                ('company_email', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_proof', models.FileField(upload_to='User_proof/')),
                ('company_photo', models.FileField(upload_to='User_photo/')),
                ('company_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
